### ISSUE TITLE
不太明白你这个模块是做什么？ ORM？

### ISSUE THREAD

**Issue by rfyiamcool** [ligyxy/DictMySQLdb#1]
不太明白你这个模块是做什么？ ORM？

**Comment by gyli** [comment]
@rfyiamcool MySQL class。它只拼接sql语句，并不映射到对象上。我在写数据处理的脚本时用这样的类，避免写太多的sql语句。

**Comment by rfyiamcool** [comment]
刚才粗略的看了下代码已经知道答案了，我刚要Close， 你就回答了.  

写的不错  ! 赞一个 ！
