### ISSUE TITLE
How about a function to return a list of distinct values from a column?

### ISSUE THREAD

**Issue by sayanarijit** [ligyxy/DictMySQLdb#5]
If you agree that it would be worth the time. If you are busy, I am willing to contribute.... :)

**Comment by gyli** [comment]
Hi. DISTINCT keyword is supported in DictMySQL.

You can do something like 
`mysql.select(table='jobs', columns=['#DISTINCT id', 'value'], where={'value': {'$LIKE': 'Art%'}})`

**Comment by sayanarijit** [comment]
Great.. I didn't notice it... However, after querying with this function, we will have to make it a list manually.... I'm taking about an inbuilt function that returns a list by default... just like get() returns one single value...

**Comment by sayanarijit** [comment]
I meant 1 dimension list like ['dog','cat','apple'] ...

**Comment by gyli** [comment]
I see what you are saying and I have thought about it when developing. The key problem here is that it is useful when you only select one field, which limits the usage scenario a lot.

I think it could be a future function and I will leave this as an open ticket.

**Comment by sayanarijit** [comment]
We can also do something like this:

db.list(table='animals', column='breed')
['cat', 'dog', 'cat', 'cat', 'dog]

db.list(table='animals', column='#DISTINCT breed')
['cat', 'dog']

Even though it queries only one column, I think it will be very helpful... Just like the get() function.

**Comment by DEMG-DEV** [comment]
Maybe you close this issue if this is no needed, if you need this let me know and i work on this.

**Comment by sayanarijit** [comment]
Let me close it. I like this library's simplicity and minimal design. Since Python already provides so many elegant ways of list creation, addition of this function won't make much difference anyway.
