### ISSUE TITLE
fun upsert  issue

### ISSUE THREAD

**Issue by luokizz** [ligyxy/DictMySQLdb#6]
debug mode ouput sql like this:
`INSERT INTO `cates` (`size`, `cname`) VALUES (1, 'test') ON DUPLICATE KEY UPDATE size=size;`

i want to increase size 's value, but it doesn't work.
i need exec mysql like this:
`INSERT INTO `cates` (`size`, `cname`) VALUES (1, 'test') ON DUPLICATE KEY UPDATE size=size+1;`
How i set the params?
i have try mysql.query to exec, but alse doesn't work.

**Comment by gyli** [comment]
Unfortunately the current upsert method only supports fixed value, like the first query.

If you want exactly the same as the second query, you have to use mysql.query() method, which is just like cursor.execute(query) in pymysql.

**Comment by gyli** [comment]
I do notice that DictMySQL only supports very basic and limited queries. The next phase of this project is not adding full SQL commands support, but a new project allowing translating from JSON to SQL, which will support all SQL queries including sub-query.
